### PR TITLE
Replaced old VerySimpleXml with current 3.0.0 version with doSimplifyTextNodes support

### PR DESCRIPTION
**Pull request by Dennis1000**
I've added an "doSimplifyTextNodes"-option in the current document parsing that can be removed in order to be standard-parsing compliant.

VerySimpleXml treats single nodes with text-only as a simple textnode:

`<node>text</node>`

is just one node with NodeType=ntText, whereas normal XML parsing would result in an Element node with a Text node as a child, thus diffrerent text/element-node counts in the test. Well, it's called VerySimpleXml, so it simplifies the DOM node structure ;-)

With that option removed it should now complete all tests ;-)

### CODE REVIEW

**Comment by neslib** [comment]
Thanks! I will look into this pull request a bit later. I will the rerun the performance tests and update the charts in my blog post accordingly.

Are you going to publish version 3.0 yourself as well (on your GitHub account)? I would prefer to only include test results for libraries that are publicly available.

**Comment by Dennis1000** [comment]
Yes, that's the version that will be published. I'm just running some tests and may adjust the SearchNode-function and add some FindRecursive functions that aren't used in the PerfTest. You may wait for the "final" published version as well, of course.

**Comment by neslib** [comment]
I merged your pull request and reran the performance tests. Seems like your library also loads a bit faster now and uses less memory with these changes.

I updated the blog post as well to show the updated charts.

**Comment by Dennis1000** [comment]
Yes, by removing the workarounds for the old Delphi versions, it now loads a little bit faster. The VerySimpleXML version in the pull request is now exactly the version currently available in the v3-branch in the VerySimpleXML github repository.
Thanks for updating the Tests ;-)

**Pull request merged**
